version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spassu-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - spassu-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: spassu-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - spassu-network
    depends_on:
      - app
      - node

  node:
    image: node:18-alpine
    container_name: spassu-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - spassu-network
    ports:
      - '5173:5173'

  db:
    image: postgres:15-alpine
    container_name: spassu-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-spassu}
      POSTGRES_USER: ${DB_USERNAME:-spassu}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - spassu-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-spassu} -d ${DB_DATABASE:-spassu}']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  spassu-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local